# Generated by Django 4.2.7 on 2024-08-06 11:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0002_registrations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registrations',
            new_name='Registration',
        ),
    ]
