# Generated by Django 4.2.7 on 2024-08-13 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_suggestionbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestionbox',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.event'),
        ),
    ]
