# Generated by Django 4.2.7 on 2024-08-13 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_alter_suggestionbox_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestionbox',
            name='category',
            field=models.CharField(choices=[('Suggestions', 'Suggestions'), ('Complaint', 'Complaint')], default='Suggestions', max_length=35),
        ),
    ]
