# Generated by Django 4.2.7 on 2024-08-13 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_alter_suggestionbox_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestionbox',
            name='category',
            field=models.CharField(choices=[('Suggestions', 'Suggestions'), ('Complaint', 'Complaint')], default='Suggestions', help_text='Please select the nature of our suggestion!', max_length=35),
        ),
        migrations.AlterField(
            model_name='suggestionbox',
            name='description',
            field=models.TextField(help_text='Share your experience. we would like to hear from you!'),
        ),
        migrations.AlterField(
            model_name='suggestionbox',
            name='event',
            field=models.ForeignKey(blank=True, help_text='If your sharing something regarding event please select that event!', null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.event'),
        ),
    ]
